export const GET_USERS_START = "GET_USERS_START";
export const GET_USERS_FAILURE = "GET_USERS_FAILURE";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";

export const CREATE_USER_START = "CREATE_USER_START";
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";


export const LOGIN_USER_START = "LOGIN_USER_START";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";

export const EDIT_USER_START = "EDIT_USER_START";
export const EDIT_USER_FAILURE = "EDIT_USER_FAILURE";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
